### ISSUE TITLE
Facebook and Gmail login and sign up

### ISSUE THREAD

**Issue by sandile11** [Socialate/furry-sniffle#9]
This doesn't want to work on my phone, the same story on Musa's phone. Does it work on the emulator?

**Comment by francis-iam** [comment]
let me take a look at it and I will get back to you.

**Comment by francis-iam** [comment]
the Gmail login works just fine, you cant use the same email address for the different login methods. just keep that in mind.

**Comment by francis-iam** [comment]
facebook works just fine as well on the emulator I can debug the problem. cause I'm not experiencing it on my side. attach your phone via USB and check the logs.

**Comment by sandile11** [comment]
This issue has been fixed.
